// creating a class to create drops
class Drop{
  
 
 float x = random(width);
 float x2 = random(5,25); 
 //float y = random(-500, -200);
 float y = random(50, 200);
 float z = random(0,20);
 
 
 // speed takes random value genterated by z and applies a speed depending on that number
 // the bigger the value z returns the faster the drop falls
 float speed = map(z,0,20/4,4/2,10/2);
 
 // like speed, len takes the value generated by z except this time it is used for the size of the shape we are generating 
 float len = map(z, 0,20,5,30);
 
 //create a function called fall that can be later called
 void fall(){
  //when fall is called add speed to the y value of the drop
  y += speed;
  }
  
  
  
  void update(){
    //when the update function is called create an ellipse where the x(0 - width),y(50,200) and size(5,30) are randomised
   ellipse (x, y, len,len); 
   
   
   //when the mouse was in these areas i was spped to the x position making them appear like a breeze was pusshing them
   //unfortunatley this caused the sketch to crash frequently once the drops were required to display the video
   //if(mouseX < width/3){
   //     x += speed; 
   //     //y -= 1;
        
   //   }
      
   //   if(mouseX > width/1.4){
   //    x -= speed; 
   //   // y += 15;
   //   }
      
   //   else{
   //     // ellipse (x, y, x2,x2); 
   //      x += 0;
   //   }
   //when the drops travvel off screen i am moving their position back to the opposite side of the screen causing them to endlessly loop
   if(y > height){
     //float splashX = map(z,0,20,10,20);
     //float splashY = map(z,0,20,10,20);
    //// strokeWeight(splash);
     ////fill(trackColor);
     //noStroke();
     //ellipse(x,y,splashX,splashY);
     y = random(50, 200);
     x = random(width);
     
      //speed = map(z,0,20,4,10);   
   }
   
   else if(x < 0){
    x = random(width + 50, width+500); 
   }
   
   else if(x > width){
    x = random(0,-50);
   }
   
  
  }
}